### ISSUE TITLE
snapTo doesn't work in the example Expo Snack

### ISSUE THREAD

**Issue by Shawin** [kmagiera/react-native-reanimated#182]
In the [Expo Snack's Interactable demo](https://snack.expo.io/@kzzzf/interactable-demo) for "Snap To", when tapping the button once, the red circle doesn't move.

**What is expected:**
When button is tapped, the red circle moves to the next position.

**What happens:**
When button is tapped, the red circle does _**not**_ move at all.

Tapping the button multiple times in succession (within ~1s) gets the red circle to move.
The issue occurs on both iOS and Android.
Screen recording gif attached.
![reanimated_interactable_snapto_demo](https://user-images.githubusercontent.com/309610/52337048-f38d7e80-2a1f-11e9-8229-43ef4f33ff5c.gif)

**Comment by pribeh** [comment]
Experiencing this as well.

**Comment by pribeh** [comment]
Works best if you replace it with TapGestureHandler from the RNGH library.

**Comment by Shawin** [comment]
> Works best if you replace it with TapGestureHandler from the RNGH library.

Do you mean replace the button and it's onPress with TapGestureHandler and onHandlerStateChange? That doesn't work for me, unless I don't check for a state, in which case it just runs the snapTo function multiple times (i.e . through the BEGAN, ACTIVE and END states).

Could you show me what you replaced, please?

I don't think that it's the correct thing to do, but the only way I could get it to work was to remove `stopClock(clock)` from [line 388 in Interactable.js](https://github.com/kmagiera/react-native-reanimated/blob/8765e8c9c755e9a247c1929ce1b28ee2f43ee1df/Example/Interactable.js#L388)

**Comment by osdnk** [comment]
@Shawin I think the way I suggested does not require stopping clock

**Comment by Shawin** [comment]
@osdnk That makes it work, **but** I think that it leaves the clock running forever or something. Let the app run for one minute and then try dragging the circle up and down the screen. It will move in a jittery, laggy way.

**Comment by osdnk** [comment]
Fixed with #197

**Comment by chrise86** [comment]
I'm still getting this issue with the latest :(

**Comment by alisherakb** [comment]
Still experiencing an issue with snapTo :/

**Comment by kreshnikalidema** [comment]
This problem still exists. PR #197 "Add additional check for running clock for imperative snapTo" doesn’t fix it and no additional check for clock running is needed. The problem is related with `testMovementFrames` when `snapAnchor` changes. `noMoveFrameCount` stays the same (more than 10 frames) and for this reason the clock does not start to run. A quick fix is the following code. I hope next week I will have time to make a more appropriate solution for which I will create a PR.

```
      const testMovementFrames = block([
        onChange(snapAnchor.x, set(last, Number.MAX_SAFE_INTEGER)),
        onChange(snapAnchor.y, set(last, Number.MAX_SAFE_INTEGER)),
        cond(eq(advance, last), set(noMoveFrameCount, add(noMoveFrameCount, 1)), [
          set(last, advance),
          set(noMoveFrameCount, 0),
        ]),
      ]);
```
