### ISSUE TITLE
Unable to resolve "react-native/Libraries/Components/View/ViewStylePropTypes" from "node_modules/expo/node_modules/react-native-reanimated/src/createAnimatedComponent.js"

### ISSUE THREAD

**Issue by shouhuori** [kmagiera/react-native-reanimated#191]
Failed building JavaScript bundle.
React Native:0.58
Expo:32.0.0

**Comment by lindesvard** [comment]
Its solved in the latest release: https://github.com/kmagiera/react-native-reanimated/issues/186

**Comment by shouhuori** [comment]
@lindesvard ,Thanks, I downgrade `1.0.0-alpha.12` to `1.0.0-alpha.11`, and solve this problem.

**Comment by Matt-F-Wu** [comment]
Interesting, I upgraded to 1.0.0-alpha.12 and solved the problem. In alpha 12, I see the fix.

**Comment by sgehrman** [comment]
Doesn't work for me.  I have all the latest packages.  expo is importing ─ react-native-reanimated@1.0.0-alpha.11

**Comment by Xerus2000** [comment]
Even tried upgrading to 1.0.1 - still getting this error.

dependencies:
```
  "dependencies": {
    "apisauce": "^1.0.2",
    "color": "^3.1.0",
    "create-react-context": "^0.2.3",
    "expo": "^32.0.6",
    "geolib": "^2.0.24",
    "react": "^16.8.4",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-collapsible": "^1.4.0",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-maps": "^0.23.0",
    "react-native-snap-carousel": "^3.7.5",
    "react-navigation": "^3.3.2",
    "react-native-reanimated": "^1.0.1"
  },
  "devDependencies": {
    "@types/expo": "^32.0.13",
    "@types/jest": "^24.0.13",
    "@types/react": "^16.8.19",
    "@types/react-native": "^0.57.60",
    "@types/react-test-renderer": "^16.8.1",
    "react-native-typescript-transformer": "^1.2.12",
    "rimraf": "latest",
    "schedule": "^0.5.0",
    "typescript": "^3.5.1"
  },
```

**Comment by brunocrpontes** [comment]
@Xerus2000 try install with ``yarn add react-native-reanimated@1.0.1``, the problem is over the expo install not with reanimated

**Comment by jnasirur** [comment]
1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.

**Comment by stevematdavies** [comment]
This issue has caused a complete standstill of our development. Working with Expo 35 and the latest react-native-reanimated, and following the instructions here, we are getting:

`Unable to resolve "./core/AnimatedFunction" from "node_modules/react-native-reanimated/src/base.js"`

**Comment by delalama** [comment]
npm i react-native-reanimated

**Comment by keshav-optisol** [comment]
Unable to resolve module `./core/AnimatedEvent` from `node_modules\react-native-reanimated\src\createAnimatedComponent.js`:
Same issue here,what can i do?
